---

- name: Add settings to lxc containers
  ansible.builtin.blockinfile:
    path: "/etc/pve/lxc/{{ item }}.conf"
    block: |
      lxc.apparmor.profile: unconfined
      lxc.cap.drop:
      lxc.mount.auto: "proc:rw sys:rw"
      lxc.cgroup2.devices.allow: c 10:200 rwm
  with_items:
    - 100
    - 101
    - 200
    - 201
    - 202
    - 203
  notify: reboot containers
