---

- name: Disable VMs SWAP
  sysctl:
    name: vm.swappiness
    value: "0"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Check if swap is on
  shell: swapon -s
  register: is_swapon

- name: Disable SWAP
  shell: swapoff -a
  when: "is_swapon.stdout != ''"

- name: Ensure swap is disabled after reboot
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Start LXC Containers
  shell: "pct start {{ item }}"
  register: ret
  with_items:
    - 100
    - 101
    - 200
    - 201
    - 202
    - 203
    - 800
    - 801
  failed_when: '"does not exist" in ret.stderr'
  changed_when: '"already running" not in ret.stderr'