---

- name: Execute pre-tasks
  include_tasks: ./pre_tasks.yml

- name: Start LXC containers
  community.general.proxmox:
    vmid: "{{ item }}"
    api_user: " {{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    state: started
  with_items:
    - 100
    - 101
    - 200
    - 201
    - 202
    - 203
    - 800