---

- name: "Install packages"
  ansible.builtin.apt: "name={{ item }} state=present"
  with_items:
    - python3-pip

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - proxmoxer
    - requests