---

- hosts: proxmox
  roles:
  - role: hypervisor

- hosts: postgres
  become: yes
  roles:
  - role: database

- hosts: influxdb
  become: yes
  roles:
  - role: influxdb

- hosts: kubernetes
  become: yes
  roles:
  - role: kubernetes

- hosts: proxmox
  gather_facts: false
  roles:
  - role: post_install